version: 0.1

phases:
  install:
    commands:
      - echo pre_build on `date`
      - sudo apt-get update -y
      - sudo apt-get -y install yum
      - echo `yum list installed`
      - sudo yum repolist all
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Test started on `date`
      - echo `pwd`
      - echo `ls -l`
      - echo `cat /etc/passwd`
      - echo `cat /etc/lsb-release`
      - sudo useradd -p 'passWord' batchuser
      - echo `cat /etc/passwd`
      - su batchuser
      - cd ~
      - echo `pwd`
      - echo `sudo -u batchuser ls /home/batchuser`
      - echo Test completed on `date`
  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...

