version: 0.1

environment_variables:
  plaintext:
    batchuser_pass: "passWord"

phases:
  install:
    commands:
      - echo pre_build on `date`
      - sudo apt-get update -y
      - sudo apt-get -y install yum
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Test started on `date`
      - echo `pwd`
      - echo `ls -l`
      - echo `cat /etc/passwd`
      - echo `cat /etc/lsb-release`
      - sudo useradd -m -s /bin/bash  batchuser
      - echo batchuser:passWord | /usr/sbin/chpasswd
      - echo `cat /etc/passwd`
      - sudo su - batchuser
      - cd ~
      - echo `pwd`
      - sudo sh test.sh
      - echo `ls -l`
      - echo Test completed on `date`
  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...

